version: '2'
services:
  selenium-hub:
    image: selenium/hub
    logging:
      driver: 'none'
    ports:
      - 4444:4444

  node-chrome:
    image: selenium/node-chrome
    logging:
      driver: 'none'
    links:
      - selenium-hub
    depends_on:
      - selenium-hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444

  node-firefox:
    image: selenium/node-firefox
    logging:
      driver: 'none'
    links:
      - selenium-hub
    depends_on:
      - selenium-hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444

  test-machine:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    working_dir: /app
    links:
      - selenium-hub
      - node-chrome
      - node-firefox
    depends_on:
      - selenium-hub
      - node-chrome
      - node-firefox
    environment:
      - NODE_ENV=development
    command: >
      /bin/bash -c "
        while ! nc -z selenium-hub 4444;
        do
          echo waiting selenium-hub;
          sleep 10;
        done;
        echo Connected!;
        npm run test:run
      "
